# Generated by Django 3.2.5 on 2021-07-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL("""
           INSERT INTO store_collection (title)
           VALUES ('collection1')
       """, """
           DELETE FROM store_collection 
           WHERE title='collection1'
       """)
    ]
